name = "nihongo-memo"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./src"

[[d1_databases]]
binding = "DB"
database_name = "nihongo-memo-db"
database_id = "56feea26-724d-4ba5-b730-8383e674c5bc"
